title: Page
pages: false
files: true
options:
  preview: true
  status: true
  template: false
  url: true
  delete: true
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  colWidth:
    label: Column-Layout
    type: radio
    options:
      col-md-12: col-md-12
      col-md-8: col-md-8
      col-md-6: col-md-6
      col-md-4: col-md-4
