title: Page
pages: false
files: true
options:
  preview: true
  status: true
  template: false
  url: true
  delete: true
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
