title: Site
pages:
  template: default
fields:
  title:
    label: Title
    type:  text
  author:
    label: Author
    type:  text
  description:
    label: Description
    type:  text
  avatar:
    label: Avatar
    type:  image
  analytics:
    label: Google-Analytics code
    type:  text
  keywords:
    label: Keywords
    type:  tags
  copyright:
    label: Copyright
    type:  textarea
